# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

  # 📦 Step 2: Publish the project (output ready to be zipped)
- script: dotnet publish --configuration $(buildConfiguration) --output publish_output
  displayName: 'Publish'

  # 📁 Step 3: Zip the published output
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'publish_output'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(6d308cf6-c494-45e0-9eba-89af42f3ed67)'
    appType: 'webApp'
    appName: 'tomweb'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
    deploymentMethod: 'auto'
